### ISSUE TITLE
Get the Selected Option from List 

### ISSUE THREAD

**Issue by chenweidavis** [dialogflow/dialogflow-fulfillment-nodejs#101]
Hi, all. I can successfully create a list with the function getDestination(). Then,I followed the guide [https://developers.google.com/actions/assistant/responses#list](url) from Google to do the reaction of list and create the function getOption(), and also insert the Event "actions_intent_OPTION" into my intent 'actions.intent.OPTION' in Dialogflow, but I keep  getting the Error from Google Assistant, the error is "MalformedResponse 'final_response' must be set." when I select one option from the list. Anybody can help on it, thanks a lot.

My code is below:

`'use strict';`

`const functions = require('firebase-functions');`
`const {WebhookClient} = require('dialogflow-fulfillment');`
`const {Card,Suggestion, Payload} = require('dialogflow-fulfillment');`
`const {dialogflow,List}=require('actions-on-google');`

`process.env.DEBUG = 'dialogflow:debug'; // enables lib debugging statements`

`exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {`
	
  `const agent = new WebhookClient({request, response});`
  `const app = dialogflow({debug: true});`
  
  `console.log('Dialogflow Request headers: ' + JSON.stringify(request.headers));`
  ` console.log('Dialogflow Request body: ' + JSON.stringify(request.body));`

`function welcome(agent) {`
    `agent.add(`Welcome to the LTA Find Bus!`);`
    `agent.add(`I can help you to find the suitable bus stop, bus service, and arriving time. Where are you` `want to go?`);`
    `agent.add(new Suggestion('Bedok'));`
    `agent.add(new Suggestion('Cancel'));`
 ` }`

`function getDestination(agent) {`
   ` // Get parameters from Dialogflow to convert`
   ` const Destination = agent.parameters.Destination;`
    
    let conv=agent.conv();
	conv.ask(`User would like to go to ${Destination}. `);
	conv.ask('Please choose an bus stop:');
    conv.ask(new List({
    title: 'List of Bus Stops',
    items: {
     // Add the first item to the list
      '1': {
        title: 'Opp Our Tampines Hub - 76059',
      },
     // Add the second item to the list
      '2': {
       title: 'Blk 945 - 76111',
      }}}));
    
    agent.setContext({
      name: 'Destination',
     lifespan: 5,
     parameters:{Destination: Destination}
    `});
    
   ` agent.add(conv);
`}`

`function getOption(agent) {`
    
    const SELECTED_ITEM_RESPONSES = {
 ` ['1']: 'You selected the first item',`
 ` ['2']: 'You selected the second item',`
`};`

    app.intent('actions.intent.OPTION', (conv, params, option) => {
  `let response = 'You did not select any item';`
 ` if (option && SELECTED_ITEM_RESPONSES.hasOwnProperty(option)) {`
    `response = SELECTED_ITEM_RESPONSES[option];`
  `}`
 ` agent.add(response);`
`});`
   ` }`

  `let intentMap = new Map(); // Map functions to Dialogflow intent names`
  `intentMap.set('Default Welcome Intent', welcome);`
 ` intentMap.set('getDestination-BusStop', getDestination);`
 ` intentMap.set('actions.intent.OPTION', getOption);`
 ` agent.handleRequest(intentMap);`
  
`});`

**Comment by matthewayne** [comment]
List selection events are Action on Google specific events and are not supported by this library.  If you are building on Dialogflow with only Actions on Google in mind please use the [Actions on Google client library](https://github.com/actions-on-google/actions-on-google-nodejs) . If you are building for Actions on Google and other platforms please see the [Dialogflow fulfillment & Actions on Google client library sample](https://github.com/dialogflow/fulfillment-actions-library-nodejs).

**Comment by dbeqiraj** [comment]
If anyone is facing the same problem and don't know how to get the key of the selected item from the `List`, using `WebhookClient `this is how I managed it:

1. Add `actions.intent.OPTION` in **Events** section of the Intent that you want to be triggered when selecting an item from the `List`

2. In your **Fulfillment** code, you can access the key of the selected item like this:

```
function yourIntentFunction(agent) {
   ....
   let param1 = request.body.queryResult.outputContexts[0].parameters.param1;
   let param2 = request.body.queryResult.outputContexts[0].parameters.param2;
   ....
   
   let KEY = request.body.originalDetectIntentRequest.payload.inputs[0].arguments[0].textValue;
   ....
}
```
**Notes**:
1. I came to this solution by inspecting `request.body` object
2. I only had **1 List** in my view. I don't know what happens when you have **more than 1 List** or **1 List + 1 Carousel** in the same view. In any case, as I did, you can inspect `request.body` to see where to find the keys.

**Comment by ramyakopalli** [comment]
Hi iam using the card view to display the list of products,
           agent.handleRequest(intentHandler);
                                                                           function intentHandler(agent) {
                                                                                 agent.add(new Card({
                                                                                    title: "Hello",
                                                                                    imageUrl: imgarray1[j],
                                                                                    text: ``,
                                                                                    buttonText: prodNamearray1[j],
                                                                                    buttonUrl: "https://dialogflow.com/docs/intents/rich-messages"
                                                                          })
                                                                      );
Here I am unable to get the selected product by the user. I am using the dialogflow fulfilment through node.js

**Comment by arianyambao** [comment]
> If anyone is facing the same problem and don't know how to get the key of the selected item from the `List`, using `WebhookClient `this is how I managed it:
> 
> 1. Add `actions.intent.OPTION` in **Events** section of the Intent that you want to be triggered when selecting an item from the `List`
> 2. In your **Fulfillment** code, you can access the key of the selected item like this:
> 
> ```
> function yourIntentFunction(agent) {
>    ....
>    let param1 = request.body.queryResult.outputContexts[0].parameters.param1;
>    let param2 = request.body.queryResult.outputContexts[0].parameters.param2;
>    ....
>    
>    let KEY = request.body.originalDetectIntentRequest.payload.inputs[0].arguments[0].textValue;
>    ....
> }
> ```
> 
> **Notes**:
> 
> 1. I came to this solution by inspecting `request.body` object
> 2. I only had **1 List** in my view. I don't know what happens when you have **more than 1 List** or **1 List + 1 Carousel** in the same view. In any case, as I did, you can inspect `request.body` to see where to find the keys.

This solved my problem with the events. Thank you

**Comment by bpbutti** [comment]
> If anyone is facing the same problem and don't know how to get the key of the selected item from the `List`, using `WebhookClient `this is how I managed it:
> 
> 1. Add `actions.intent.OPTION` in **Events** section of the Intent that you want to be triggered when selecting an item from the `List`
> 2. In your **Fulfillment** code, you can access the key of the selected item like this:
> 
> ```
> function yourIntentFunction(agent) {
>    ....
>    let param1 = request.body.queryResult.outputContexts[0].parameters.param1;
>    let param2 = request.body.queryResult.outputContexts[0].parameters.param2;
>    ....
>    
>    let KEY = request.body.originalDetectIntentRequest.payload.inputs[0].arguments[0].textValue;
>    ....
> }
> ```
> 
> **Notes**:
> 
> 1. I came to this solution by inspecting `request.body` object
> 2. I only had **1 List** in my view. I don't know what happens when you have **more than 1 List** or **1 List + 1 Carousel** in the same view. In any case, as I did, you can inspect `request.body` to see where to find the keys.

The solution to grab the `KEY` of the selected option did work for me. But if you are using the the "dialogflow-fulfillment-nodejs" library, you could also do the following, where:

1. "catch_list_option" is a follow-up intent to an intent displaying a list of options
2. "catch_list_option" has "actions_intent_OPTION" defined in its Events section
3. "global_context" is an input and output context that i defined to all my intents, and where keep the parameters I will need

```js
function catch_list_option_follow(agent){
    const option_intent = agent.context.get('actions_intent_option');
    const option_key = option_intent.parameters.OPTION;
    const option_text = option_intent.parameters.text;
    agent.context.set({name: 'global_context',
                       lifespan: 1, 
                       parameters: { 
                         parameter_name: option_key
                        }});

let intentMap = new Map();
intentMap.set('catch_list_option', catch_list_option_follow);
agent.handleRequest(intentMap);
```
