### ISSUE TITLE
agent.setFollowupEvent purges agent.add

### ISSUE THREAD

**Issue by daniel-severo** [dialogflow/dialogflow-fulfillment-nodejs#102]
I'm trying to make my bot say some stuff and later trigger an Intent with an Event trigger. But, every time I have something like:

```js
agent.add('I will say something here!');
agent.setFollowupEvent('SOME_EVENT');
```

The `agent.add` command is skipped over and the bot goes directly to the intent triggered by `SOME_EVENT`.

If I remove the line of code with `agent.setFollowupEvent`, it works fine.

Is this a bug or am I misusing the api?

Cheers!

**Comment by matthewayne** [comment]
This is not a bug in the library but the way Dialogflow works.  Follow up events are a way to redirect from the currently match intent to another intent.  The currently matched intent does not have a chance to respond before it is redirected.  This means you will only have one response from the intent that is redirected to last.  You can't compile response from multiple intent responses by redirecting through multiple intents with follow up events.

When a followup event is triggered from the webhook, the event specified in the webhook response is triggered. Triggering the event through a webhook sends the request back through Dialogflow for matching without responding to the user. The response to the user is sent as if the user triggered the event that was triggered in the webhook.  After the second intent is matched by the event, Dialogflow will do any necessary work (like webhook calls or additional prompts for required parameters) and send a response back as if the second intent was the originally matched intent.

[![enter image description here][1]][1]

1. A user sends a request to Dialogflow.
1. "Intent 1" is matched by Dialogflow.
1. A webhook request is sent to your fulfillment server, which indicates that intent 1 was matched.
1. Your fulfillment server responds to the webhook request with a followup event response.
1. Dialogflow re-matches intent 2 based on the followup event sent in the webhook response.
1. Dialogflow sends a response to the user based solely on intent 2 being matched. Dialogflow may send another webhook call indicating intent 2 was matched, or send a prompt for unfulfilled required parameters (if configured) for intent 2.


  [1]: https://i.stack.imgur.com/BT0OG.png

**Comment by juliejoseph3** [comment]
Can you provide some sample code for adding a followup event? I tried to generate an event in following ways, I'm not getting any error, but the followup intent is not triggered

agent.setFollowupEvent('CUSTOMER_NAME_REQUESTED');

OR

agent.setFollowupEvent({ "name": "CUSTOMER_NAME_REQUESTED", "parameters" : { "received": "false"}});

Please help

**Comment by sarahdwyer** [comment]
@juliejoseph3 Many of the Dialogflow samples have followup events like [here](https://github.com/dialogflow/fulfillment-telephony-nodejs/blob/master/functions/index.js).

**Comment by juliejoseph3** [comment]
I did the same in code and created an intent with the event 'CUSTOMER_NAME_REQUESTED', but the followup intent is not getting triggered. Also, No error shown

What could be the reason?

**Comment by sarahdwyer** [comment]
Honestly, it could be a number of things but I think you'll find it very helpful going through the [sample](https://github.com/dialogflow/fulfillment-telephony-nodejs) to get a better idea of triggering intents in general.

**Comment by juliejoseph3** [comment]
Thankyou!

**Comment by dorronzherka** [comment]
Is there a way to do setfollowup  with agent.add()?

**Comment by abhinavkumar985** [comment]
> agent.setFollowupEvent({ "name": "CUSTOMER_NAME_REQUESTED", "parameters" : { "received": "false"}});

after two days of the struggle, this works for me. Thanks a lot. You saved me.

**Comment by davidwkaiser** [comment]
> @juliejoseph3 Many of the Dialogflow samples have followup events like [here](https://github.com/dialogflow/fulfillment-telephony-nodejs/blob/master/functions/index.js#L71).

does that fact that line 71 puts the call to setFollowupEvent inside a variable assignment create a different result than just saying agent.setFollowupEvent('call_transfer_event')? If so, how

**Comment by preetjdp** [comment]
Hey, @davidwkaiser did you figure out the reason behind the assignment?

**Comment by davidwkaiser** [comment]
> Hey, @davidwkaiser did you figure out the reason behind the assignment?

No, I didn't. I figured out a workaround and kept moving...

**Comment by Exter-dg** [comment]
While setting a followup event, if I do not provide a `agent.add()` before `agent.setFollowupEvent`, cloud console shows an error - `no responses defined for platform dialogflow_console`.

```
  function setFollow(){
   // throws error without agent.add
   agent.add("hello"); 
   agent.setFollowupEvent({"name": "myFollowup", "parameters": {"myname": "John"}});
  }
```

1. What's the reason behind this behaviour?

The above function is working fine in my code. I need to get some data from an API and set the followup event using the data. When I add `agent.setFollowupEvent` inside `then`, it is not working.

```
function setFollow(agent) {
  agent.add("hello"); 
  axios.post(url, body, {headers})
    .then (({ data }) => {
      agent.add("setting followup event");
      agent.setFollowupEvent({ "name": data.followupEventInput_name, "parameters" : { "name": data.name}});
    }) 
}
```

The API call is working correctly, and its also receiving an appropriate response. But the followup event is not being set. The first `agent.add("hello")` works (which is not the intended behaviour when there is a followup event).

2. How to solve this?

**Comment by darguez** [comment]
Just in case you didn't solve the issue, axios call is asynchronous, so function setFollow() just ends with "hello" message before receiving the data. I htink you could force waiting for axios result by defining setFollow as async function and use await.
```
async function setFollow(agent) {
  agent.add("hello");
  await axios.post(url, body, {headers})
  ...
```
