### ISSUE TITLE
Authentication with dialogflow-fulfillment-nodejs

### ISSUE THREAD

**Issue by KathyLiz** [dialogflow/dialogflow-fulfillment-nodejs#104]
Hi!
I want to migrate my webhook to dialogflow v2, but don't found any information about the authentication method with this library, please help me!

**Comment by sarahdwyer** [comment]
Hey! Check out this reference doc -- https://dialogflow.com/docs/reference/v1-v2-migration-guide but more specifically for auth go here: https://dialogflow.com/docs/reference/v2-auth-setup
