### ISSUE TITLE
How to handle list/carousel selection events ?

### ISSUE THREAD

**Issue by karanvs** [dialogflow/dialogflow-fulfillment-nodejs#105]
I have made a carousel following this example,

[link](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/master/samples/actions-on-google/functions/index.js)

How can I handle the selection event for this ?

**Comment by syedatifakhtar** [comment]
Hi,

Your link does not work for me.

I got it to work for me on a project i did earlier using

actions_intent_OPTION as an EVENT TRIGGER on a followup intent to the intent containing the carousel.

To extract the value in a parameter use #actions_intent_option.OPTION

**Comment by sarahdwyer** [comment]
@karanvs Your link is broken, can you post the code you have so far and be more specific?

**Comment by matthewayne** [comment]
List selection events are Action on Google specific events and are not supported by this library.  If you are building on Dialogflow with only Actions on Google in mind please use the [Actions on Google client library](https://github.com/actions-on-google/actions-on-google-nodejs) . If you are building for Actions on Google and other platforms please see the [Dialogflow fulfillment & Actions on Google client library sample](https://github.com/dialogflow/fulfillment-actions-library-nodejs).
