### ISSUE TITLE
French - 2 millions not detected as number

### ISSUE THREAD

**Issue by kofeetokode** [dialogflow/dialogflow-fulfillment-nodejs#107]
Hello,
I have an intent with a @sys.number parameter. 
In french, when I say "deux millions", Dialogflow doesn't understand that "2 millions" means 2 000 000. If I type "2 million" without the "s" instead of "2 millions", it is recognized as "2 000 000".

Millions in french language could be either plural or singular. Is this the right place for this issue?

Thanks!

**Comment by sarahdwyer** [comment]
For actions that need multi-language support in Dialogflow I would check this out: https://dialogflow.com/docs/multi-language

**Comment by kofeetokode** [comment]
Hello Sarah,
Thanks for your answer, I have already activated multi-language support.
My problem is that while doing slot filling for @sys.number in French language, "5 millions" isn't recognized and is considered as "5" instead of "5 000 000".

Thanks

**Comment by sarahdwyer** [comment]
Right I see, okay well I recommend highlighting the entire phrase "deux millions" or "2 millions" and selecting @sys.number:number for the variations you'd expect from users. You can also add your own entities via uploading CSV or JSON files if you'd prefer. For more on that: https://dialogflow.com/docs/entities

**Comment by kofeetokode** [comment]
Hello Sarah,
I believe this should be fixed on the Dialogflow side since "millions" isn't recognized at all in French locale. It is only recognized if "million" isn't plural. This is a particularity of the French language that "million" can be singular/plural.

If I extend the @sys.number by creating a new entity that would inherit from @sys.number and add
"1-9 millions" to that entity, I would consider that more as a hack than a fix. I also don't know how I could extend @sys.number by creating my own entity :

```
>1000000 1 million
>2000000 = 2 millions
>3000000 = 3 millions
...
>9000000 = 9 millions
>@sys.number = @sys.number
```

**Comment by KoffeeToKode** [comment]
Hello,
any updates?

Thanks!
