### ISSUE TITLE
Context names are coerced into lower case

### ISSUE THREAD

**Issue by cchan** [dialogflow/dialogflow-fulfillment-nodejs#109]
```
  agent.setContext({
    name: "storeName",
    lifespan: 2,
    parameters: {abc: 123}
  });
```

results in a `agent.contexts` containing a "storename" but no "storeName". Is this a known feature/bug?

**Comment by matthewayne** [comment]
This lower casing happens on the Dialogflow product itself (and not this library) when using the v2 API. I'll work with the team to get this documented on http://docs.dialogflow.com
