### ISSUE TITLE
`getContext("facebook_location")` is not documented anywhere

### ISSUE THREAD

**Issue by cchan** [dialogflow/dialogflow-fulfillment-nodejs#110]
This probably isn't the right place to put this as an issue, but the fact that DialogFlow inserts a context called "facebook_location" when it receives a location payload from Facebook is a very useful fact. Is this documented anywhere?

**Comment by KoffeeToKode** [comment]
Hello cchan,
I've found this : https://dialogflow.com/docs/events#facebook_location.

It's not exactly what you were looking for.

Usually, I would use the event that is supposed to be triggered by other integrations. And once this event is triggered, I will examine the request payload and use it.

In this case, I would have seen the facebook_location context.

**Comment by matthewayne** [comment]
Thanks for the feedback. We'll be updating the documentation KoffeeToKode linked to above. I the mean time here is some more info on how to work with Facebook Messenger location on Dialogflow: 

1. Create an intent to request the location using a custom payload:

{
  "facebook": {
    "text": "give me your location please",
    "quick_replies": [
      {
        "content_type": "location"
      }
    ]
  }
}

2. Create another intent to process the location and set the event to FACEBOOK_LOCATION. In the webhook, you'll receive the latitude and longitude from the originalRequest field:

{
  "originalDetectIntentRequest": {
    "source": "facebook",
    "payload": {
      "postback": {
        "data": {
          "lat": 14.556761479425,
          "long": 121.05444780425
        },
        "payload": "FACEBOOK_LOCATION"
      },
      "sender": {
        "id": "1588949991188331"
      }
    }
  }
}

For more information see Facebook Messenger's API documentation for sending location: https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies#locations

**Comment by treberlagrosa** [comment]
hi can i get extract the lat and long from that request and put it in a variable.
this is my code and I'm using a custom payload
![opera snapshot_2018-11-08_160656_stackoverflow com](https://user-images.githubusercontent.com/38646795/48185572-5e231580-e370-11e8-937d-bf754e1fa761.png)

**Comment by maganap** [comment]
@matthewayne Is there a similar event to `FACEBOOK_LOCATION` but for Facebook card postbacks? (like a `FACEBOOK_POSTBACK` event or something). I mean, to handle the postback field from tapping a card on Facebook.

I've read a few answers saying that Facebook postback field is send directly as a user utterance, it doesn't trigger any specific event. But all those answers were from more than a year ago. Are there any other options now?
TIA
