### ISSUE TITLE
Typo in Documentation addResponse_

### ISSUE THREAD

**Issue by roxor1909** [dialogflow/dialogflow-fulfillment-nodejs#111]
WebhookClient.addResponse_(response) is not a function.

I can use add, but not addResponse_ .
What is the correct function name for sending only a single response?

**Comment by roxor1909** [comment]
docs/WebClient.md

**Comment by sarahdwyer** [comment]
add is the correct function to use to add a single response and addResponse_ is a private function for the library.

**Comment by roxor1909** [comment]
Maybe the method should be removed or marked as private.
