### ISSUE TITLE
Which Actions on Google features doesn't this library support?

### ISSUE THREAD

**Issue by RayBB** [dialogflow/dialogflow-fulfillment-nodejs#112]
In the readme it says 

> If you are only interested in building Dialogflow fulfillment for the Google Assistant and don't plan on using other integrations, please use the Actions on Google NPM module (actions-on-google) which supports all Actions on Google features.

Could anyone provide some info on what features we would miss out on if we use this library instead of the actions-on-google one?

Edit: Just realized questions should be posted on SO. https://stackoverflow.com/questions/51601555/which-actions-on-google-features-doesnt-dialogflow-fulfillment-nodejs-support

**Comment by sarahdwyer** [comment]
Fulfillment supports: Text, Cards, Images, Suggestion Chips (aka quick replies), Payloads (platform specific responses). If you're developing for the Google Assistant (and not any other platforms) consider using the Actions on Google library).
