### ISSUE TITLE
When using agent.parameters.custom-parameter-name does not match Parameter Name

### ISSUE THREAD

**Issue by skryshtafovych** [dialogflow/dialogflow-fulfillment-nodejs#114]
When using agent.parameters.custom-parameter-name does not match Parameter Name if (-) is included in Name
`console.log("Parameters",agent.parameters.date);
console.log("GameType",agent.parameters.game-types);`

**Comment by KoffeeToKode** [comment]
Hello skryshta,
I would not recommend using hyphen in parameter names. I had the same problem and solved it by using camelCase parameters name.

Underscore might work, but I haven't try it.

**Comment by skryshtafovych** [comment]
I was able to fix by using like so``agent.parameters["game-types"]`` please let me know if this is bug or expected behavior.

**Comment by sarahdwyer** [comment]
Use key notation instead of dot notation, that should work. 

https://stackoverflow.com/questions/7122609/how-do-i-reference-a-javascript-object-property-with-a-hyphen-in-it
