### ISSUE TITLE
French - 2 millions not detected as number

### ISSUE THREAD

**Issue by KoffeeToKode** [dialogflow/dialogflow-fulfillment-nodejs#116]
Hello,
I have this issue that have been closed, but I still need help with it :
[Link to issue](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/107)

Thanks.

**Comment by matthewayne** [comment]
Hi, this issue tracker is for the Dialogflow fulfillment library not Dialogflow the product.  If you have an issue with Dialogflow the product please see https://dialogflow.com/support
