### ISSUE TITLE
No responses defined for platform: GOOGLE_TELEPHONY 

### ISSUE THREAD

**Issue by skryshtafovych** [dialogflow/dialogflow-fulfillment-nodejs#117]
Error: No responses defined for platform: GOOGLE_TELEPHONY
    at WebhookClient.send_ (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:488:13)
    at promise.then (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:306:38)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by nathanjliu** [comment]
This may happen when there is a webhook error unrelated to the Phone Gateway. Check your fulfilment code and other integrations!

You need to share some more information about when this is happening to get proper help.

**Comment by skryshtafovych** [comment]
Hey @nathanjliu thanks for reply,

So one of my intents is setup to have a custom webhook integration... which i setup through your guys example with firebase cloud function and have extended it. The webhook works no problem with google assistant,Web Chat and other integrations. I set the integration 
"Response from this tab will be sent to the Telephony integration.
Use response from the DEFAULT tab as the first response." for the Telephone Tab in that specific Intent and enabled Text to Speech. Am i missing something. Shouldn't the Default response automatically be forwarded to Telephone Response. The Output audio is displayed inside the simulator but when making call do not hear response.

**Comment by nathanjliu** [comment]
@skryshtafovych Yes, that is strange. In your webhook code are you defining any other particular platforms to send responses to? For example, using `if (agent.requestSource === agent.ACTIONS_ON_GOOGLE) {}`

**Comment by skryshtafovych** [comment]
Any Updates @nathanjliu Here is what the code looks like [GIST](https://gist.github.com/skryshtafovych/30d73f210b777142d811dbacbd986377)

**Comment by nathanjliu** [comment]
@skryshtafovych Try wrapping your Suggestions and Card in

`if (agent.requestSource === agent.ACTIONS_ON_GOOGLE) {}`

leaving the message outside.

**Comment by skryshtafovych** [comment]
That Fixed It Great Thanks @nathanjliu updated [GIST](https://gist.github.com/skryshtafovych/30d73f210b777142d811dbacbd986377) to reflect

**Comment by sarahdwyer** [comment]
Based on the Error: No responses defined for platform: GOOGLE_TELEPHONY, all you need to do is ensure that for all intents that you've enabled the toggle `use DEFAULT response first` under the Telephony tab.

<img width="917" alt="screen shot 2018-10-18 at 8 51 33 am" src="https://user-images.githubusercontent.com/11345614/47397387-dbe5f080-d6e3-11e8-9546-d14abb8bd82b.png">

**Comment by ChennyBaBy** [comment]
@sarahdwyer I'm getting this error too, I've also set all the intents with the Telephony using the default response.
Our fulfilment uses a async call to get the data:

```js
 return axios.get('https://www.something.com/search.json?keywords=' + make )
      .then((response) => {
        
        agent.add(`I have found a ${response.make}, Is this what you are looking for? `)
      })
```

Error:
`Error: No responses defined for platform: GOOGLE_TELEPHONY
    at WebhookClient.send_ (/srv/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:488:13)
    at promise.then (/srv/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:306:38)`

**Comment by pranjal4697** [comment]
@ChennyBaBy  Were you able to solve this issue? If so, how did you do it?

**Comment by ChennyBaBy** [comment]
Nope!

**Comment by gad2103** [comment]
this is still an issue. i'm getting the same error after following the advice here.

**Comment by ilKhr** [comment]
Hi, 
I  faced this problem and the following helped me  
`agent.end("");`

This needs to be inserted at the end of the function
Try it

**Comment by estelle97** [comment]
Error: No responses defined for platform: DIALOGFLOW_CONSOLE     at WebhookClient.send_ (/workspace/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:488:13)     at promise.then (/workspace/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:306:38)     at process._tickCallback (internal/process/next_tick.js:68:7) |  
-- | --


i have this error please help me

**Comment by gjvanouwendorp** [comment]
I was struggling with this error for hours, only to find out I needed to change these 2 little things:
- in package.json, change the version of "dialogflow-fulfillment" to "0.6.1" (instead of 0.5.0)
- make sure your intent has at least 1 default response in the bottom section of the intent configuration screen (Dialogflow ES)
