### ISSUE TITLE
FB: set messenger_extensions: true

### ISSUE THREAD

**Issue by cara** [dialogflow/dialogflow-fulfillment-nodejs#122]
Is it somehow  possible to set messenger_extensions: true in fb messenger?
Perhaps even as default true for webview?

Like it seems Payload is the only possibility for this add the moment?

**Comment by matthewayne** [comment]
This library does support platform-specific (e.g. Facebook, Actions on Google, Slack) features including Facebook Messenger configurations.  Please use Payload for platform specific communication.
