### ISSUE TITLE
SSML breaks SimpleResponsesJson

### ISSUE THREAD

**Issue by Timovdw** [dialogflow/dialogflow-fulfillment-nodejs#128]
Hi,

When trying to use SSML in a Google Assistant Simple response, there is an error in the riechResponseMapping of the text.

The request contains the message like this:

``` "fulfillmentMessages": [
      {
        "platform": "ACTIONS_ON_GOOGLE",
        "simpleResponses": {
          "simpleResponses": [
            {
              "ssml": "<speak>test</speak>"
            }
          ]
        }
...
```

In v2-agent.js this gets treated  in `getConsoleMessages_`:

```simpleResponses: this.convertSimpleResponsesJson_,```

which tries to convert this into a Text response, but it uses the textToSpeech field which is not there:

```
  convertSimpleResponsesJson_(messageJson, platform) {
   return new Text({
     text: messageJson.simpleResponses.simpleResponses[0].textToSpeech,
     platform: platform,
   });
```

Later on in the code I can find in `text-response.js` references to SSML suppossedly being used this way.

Steps to reproduce: create intent with Google Assistent response, add 'simpleresponse' and use `<speak>test</speak>` as message

**Comment by Fleker** [comment]
Can you use the [actions-on-google Node.js library](https://github.com/actions-on-google/actions-on-google-nodejs) instead?

**Comment by LukeJanissen** [comment]
I've got the same issue, haven't found a fix yet. Isn't there any way to use this library in combination with ssml?

**Comment by sarahdwyer** [comment]
@Timovdw @LukeJanissen Make sure you've enabled Beta features and APIs in your agent's settings > Save > then go up to the Speech tab where you can enable `Automatic Text-to-Speech` > Save.  You'll be easily able to use SSML with AoG or Telephony.

**Comment by LukeJanissen** [comment]
@sarahdwyer Thanks for the response, but this didn't fix the issue. I'm using the Google Assistant Simple response SSML output. I guess this option is not yet supported in this SDK?

**Comment by matthewayne** [comment]
this will be fixed in v0.6.2

**Comment by LukeJanissen** [comment]
I still can't use ssml with this SDK. When will this be fixed? It's almost two months ago now

**Comment by sarfarazmadhia** [comment]
Can we use SSML in dialogflow JSON Response from webhook i.e. without using Google Assistant client library. Basically I would like to return SSML subalias in the response from my webhook hosted on AWS Lambda. I tried to search if it is possible using dialogflow JSON response, but not able to find it anywhere.
