### ISSUE TITLE
Custom payload for facebook fails silently

### ISSUE THREAD

**Issue by positlabs** [dialogflow/dialogflow-fulfillment-nodejs#13]
I'm trying out the custom payload responses for Facebook, but so far it's a dud. I pulled a response from the messenger examples. 

    let id = request.body.originalRequest.data.sender.id
    var messageData = {
        recipient: {id},
        message: {
            attachment: {
                type: 'template',
                payload: {
                    template_type: 'button',
                    text: 'This is test text',
                    buttons: [{
                        type: 'web_url',
                        url: 'https://www.facebook.com/fbcameraeffects/tryit/168878713921569/',
                        title: 'Open Camera Effect'
                    }, {
                        type: 'postback',
                        title: 'Trigger Postback',
                        payload: 'DEVELOPER_DEFINED_PAYLOAD'
                    }, {
                        type: 'phone_number',
                        title: 'Call Phone Number',
                        payload: '+16505551234'
                    }]
                }
            }
        }
    }
    let payload = new Payload(agent.FACEBOOK, messageData)
    agent.add(payload)

Is there something I'm missing? The webhook execution finishes, but nothing shows up in messenger.

**Comment by positlabs** [comment]
Looking at the tests, I see the objects aren't exactly the same as in the facebook examples. Using the message object as the payload does the trick.

    messageData = {attachment: ...}

I am a little confused about why there is no error message for malformed payloads. Would that be something that could be handled by this lib, or would it be the onus of Facebook or Dialogflow?

**Comment by matthewayne** [comment]
I understand the pain here, but unfortunately checking the validity of the payload for a evolving 3rd party API would be pretty difficult.  The library support custom payloads for all of Dialogflow's (16 integrations)[https://dialogflow.com/docs/integrations/] and validating the payloads for all platforms and keeping up with all the API changes is out of scope for this library.

I'll leave this open for comments as we could add checking/suggestions for some common payload issues, like the one you ran into above.
