### ISSUE TITLE
Long pause on first telephony call of the morning

### ISSUE THREAD

**Issue by nathanjliu** [dialogflow/dialogflow-fulfillment-nodejs#131]
I'm using a workaround where a parameter is passed automatically to the agent when using the phone gateway. But after a long idle period, there is an extended pause before the welcome message is played and the phone gateway begins listening, causing an error.

I have recordings of what happens on the first call of the day, and immediate subsequent calls below. Note that the quick 'ID' speech is the welcome message for the phone gateway.

First call:
https://instaud.io/2FIy

Subsequent calls:
https://instaud.io/2FIz

Has anyone got either a workaround, or info on after how long the phone gateway goes to 'sleep'/if this is intended behaviour.

**Comment by sarahdwyer** [comment]
@nathanjliu Can you include your work thus far?

**Comment by matthewayne** [comment]
hi @nathanjliu this is a place to file issues on the library itself not Dialogflow the product/service.  If you are having issues with the product please see Dialogflow's user forums or if you are having a technical issue ask a question on StackOverflow.
