### ISSUE TITLE
Custom payload

### ISSUE THREAD

**Issue by GauravGaikwad94** [dialogflow/dialogflow-fulfillment-nodejs#132]
I want to show some link with title in my UI, I am using angular to create UI. 
I am trying to add custom payload in fulfillment using nodejs code but this payload is not adding in response.

Here is my code:
```javascript
const {Payload} = require('dialogflow-fulfillment');
agent.add(new Payload("custom_payload", {
  "results": [
    {
      "Tilte": "Some text",
      "Link": "example.com"
    },
    {
      "Tilte": "Some other text",
      "Link": "adfd.com"
    }
  ]
}
));
```

**Comment by sarahdwyer** [comment]
Might not work because it seems you have the field `tilte` instead of `title`

**Comment by GauravGaikwad94** [comment]
It was typo error,but It was in valid json format, I have corrected and tried again but still it is not visible in response.

**Comment by defihition** [comment]
https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/93
custom payload is added  only specific platforms which is first parameter...

**Comment by wisewap** [comment]
Checkout this solution via this link on stackoverflow. (https://stackoverflow.com/questions/54953346/using-telegram-keyboardbutton-in-dialogflow-to-get-users-phone-number/54966997#54966997)
