### ISSUE TITLE
Dialogflow Integration with Google Maps in Python/Flask 

### ISSUE THREAD

**Issue by sarahdwyer** [dialogflow/dialogflow-fulfillment-nodejs#134]
To brief in about my problem
i want to trigger the" actions on google helper intents" from my code webhook / flask application.

Few more details:

->am using python and i have used heroku virtual environment for deploying the app 
i have tried to import googlemaps and call geolocate method but it is expecting atleaset one attribute and i am unable to figure out what is the input parameter 

Thanks in advance any help is appreciated

_Originally posted by @nuronics in https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/9#issuecomment-421467106_

**Comment by code-demoe** [comment]
Did you find any solution to this? Please share.
