### ISSUE TITLE
i want to access client current location

### ISSUE THREAD

**Issue by nuronics** [dialogflow/dialogflow-fulfillment-nodejs#135]
i have a python script which i have deployed on heroku. so my requirement is i want to access user/client's current location. to achieve this their are inbuilt actions-on-google helper intents.
can anyone suggest me how can i trigger those inbuilt intents using python script their is already a node.js script to this. i need a python script to do the same
or any workaround is also appreciated

**Comment by sarahdwyer** [comment]
@nuronics This is the Node.js client library for Dialogflow, for more information on current location you can check out this [article](https://medium.com/google-developer-experts/handling-permissions-with-dialogflow-and-actions-on-google-b08c8f228c00).
