### ISSUE TITLE
How to do SignIn with Fulfillment SDK

### ISSUE THREAD

**Issue by vairaselvam** [dialogflow/dialogflow-fulfillment-nodejs#137]
How to do SignIn with Fulfillment SDK. Any sample available ?

**Comment by matthewayne** [comment]
If you are using a platform specific feature like sign in, please see the platform's documentation or tooling.  This library does not support platform specific features.  Here is a sign in example for Actions on Google using Actions on Google client library (which supports Dialogflow fulfillment): https://github.com/actions-on-google/dialogflow-google-sign-in-nodejs
