### ISSUE TITLE
Decode pay load from Google ID token using Fulfillment SDK

### ISSUE THREAD

**Issue by vairaselvam** [dialogflow/dialogflow-fulfillment-nodejs#141]
After the user authorizes action to access their Google profile, will receive a Google ID token that contains the user's Google profile information in every subsequent request to the SIGN_IN action.

To access the user's profile information, we need to first validate and decode the Google ID token by using "JWT token decoding library". But Actions-On-Google sdk automatically takes care decoding. How to receive the decoded pay load from Google ID token using Fulfillment SDK ?

**Comment by matthewayne** [comment]
This library does not support platform specific features like Actions on Google's sign in.  If you need support for Actions on Google specific features please use the Actions on Google library (which supports Dialogflow fulfillment).
