### ISSUE TITLE
How to conditionally end conversation in telephony

### ISSUE THREAD

**Issue by RezaRahmati** [dialogflow/dialogflow-fulfillment-nodejs#142]
Hi

In editing intent there is a switch at the bottom of page as "set this intent as the end of conversation" and in telephony it will hangup the phone.

Now I have an action which has a condition and might end the conversation or add another context to continue conversation. So I can't set that option "on" on my intent, I was wondering is there any way to set it on webhookclient (agent)?

**Comment by poush** [comment]
One simple would be to send a follow-up intent from your webhook to the intent which has nothing other than end conversation switched on.

**Comment by jddsoftware** [comment]
Yes! you're looking for agent.end(string). For example:
`function welcome(agent) {
    try {
        const incomingNumber = agent.originalRequest.payload.telephony.caller_id
        //todo: check phone number whitelist
        if (!incomingNumber || incomingNumber !== '+18888888888'){
            agent.end('good bye')
            return
        }
    } catch (error) {
        console.log(`got this error: ${error}`)
        agent.end('good bye')
        return
    }
}`

Note: I made a modification to v2-agent.js on line 251 of the nodejs client library:

responseJson.triggerEndOfConversation = this.agent.endConversation_;
changed to:
responseJson.endInteraction = this.agent.endConversation_;

**Comment by sarahdwyer** [comment]
@RezaRahmati 

Given the conditional user paths and in general with agent design, it makes the most sense to use two followup intents (one set to continue the conversation and the other set as end of conversation).

**Comment by deed02392** [comment]
Trying to use `.end()` I get the error: `Cannot find field: triggerEndOfConversation in message google.cloud.dialogflow.v2.WebhookResponse`

**Comment by Shajeel-Afzal** [comment]
Hi @RezaRahmati, did you find a solution for this problem?

**Comment by RezaRahmati** [comment]
> Hi @RezaRahmati, did you find a solution for this problem?

Not actually

**Comment by mv-aspect** [comment]
Last commit in this project says DialogFlow looks like the next project to be killed by Google. How can they really leave a bug like this open for so long in the most frequently used SDK, i.e., the node.js SDK?

**Comment by mv-aspect** [comment]
jddsoftware has the right fix. I pushed into a branch at I https://github.com/mv-aspect/dialogflow-fulfillment-nodejs
