### ISSUE TITLE
agent.add sending to every platform?

### ISSUE THREAD

**Issue by secato** [dialogflow/dialogflow-fulfillment-nodejs#144]
Hi people

I am testing this lib and the only thing I am doing is sending back the consoleMessages like the code below: 
`agent.add(agent.consoleMessages)`

But when I test on messenger  I realize that I am getting all messages, including the default messages.

**PS:** I not enabled the option "Use response from the DEFAULT tab as the first response."

**Comment by naranjja** [comment]
`agent.add` is not working for me on Facebook Messenger for some reason.

**Comment by matthewayne** [comment]
@secato What behavior are you expecting?

**Comment by remvil** [comment]
Hi, i have the same problem I am trying to call 

```function myFunc(agent) {
   var uri='some/api/uri';
   return new Promise((resolve, reject) => {
        http_request(uri).then(async function(data) {
          var jsonData = JSON.parse(data);
          var resp = jsonData.d.f;
          for (let i=0; i<3; i++){
            agent.add(new Card({
              title: resp[i].nome,
              text: resp[i].indirizzo + '\nOrari di apertura: ' + resp[i].orario,
              buttonText: 'Vai in ' + resp[i].indirizzo,
              buttonUrl: 'https://www.google.com/maps/search/?api=1&query=' + resp[i].lat + ',' + resp[i].lon
            }));
          }
          return resolve();
        }).catch(function(err) {
          return resolve();
        });
      });
     }
```
And I can see cards only on Telegram, it cannot show cards on Dialogflow Messenger and Facebook Messenger.

this function is called via ```intentMap.set ('search.Farmacie', myFunc);``` where search.Farmacie is a specific Intent.
It only works on Telegram. I expect that also on Facebook Messenger and Dialogflow Messenger you can see the cards as on Telegram.

Can someone help me?
