### ISSUE TITLE
Missing dependency on actions-on-google

### ISSUE THREAD

**Issue by JaTvoiRabotnik** [dialogflow/dialogflow-fulfillment-nodejs#145]
I tried deploying a fulfillment on Google's app engine. I set up the dependency on package.json to have "dialogflow-fulfillment": "^0.5.0", but I got error: Cannot find module 'actions-on-google'. 

I am not using actions-on-google explicitly on my code, but I notice that it is a requirement on line 16 of dialogflow-fulfillment.js. This dependency is not on the package.json of the library. Should it be?

Right now I get around this issue by declaring the dependency explicitly on my package.json, but that sounds like the wrong thing to do.

**Comment by matthewayne** [comment]
It is the right thing to do.  Sorry for the confusion.  This is a compromise to allow you to use both the Dialogflow fulfillment library and the Actions on Google library at the same time.  If `actions-on-google` was made a dependency of the Dialogflow fulfillment library between the library depended on by the Dialogflow fulfillment library and your code could (and did) cause issues.  To fix this issue `actions-on-google` was made a peer dependency, meaning that the library and your code use the same version of the `actions-on-google` library.  This has the unfortunate side-effect of:

1. requiring the `actions-on-google` library installation for use of the `dialogflow-fulfillment` library even if you don't use the `actions-on-google` library integration and 
1. `npm install` not installing `actions-on-google` if not explicitly added to your `package.json`

**Comment by ameyn21** [comment]
Thanks @matthewayne ! that saved my efforts.
