### ISSUE TITLE
 agent.getContext("contextName") just not working

### ISSUE THREAD

**Issue by malikasinger1** [dialogflow/dialogflow-fulfillment-nodejs#154]
I understand it is depricated but it doesnt mean it shoudl not work, new systex is even dont exist in the doc and example reopos, I must say what the f***

**Comment by malikasinger1** [comment]
I have v1 agent and have lots of contexts but when i m getting it is returning empty array

**Comment by nathanjliu** [comment]
@malikasinger1 I don't really know why they closed this with no comment because they are working on fixing the documentation and message though as promised here: https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/147 :)

**Comment by malikasinger1** [comment]
@matthewayne why you closed this issue? isn't it an issue? do have any example of new syntex if yes please dont feel hesitation in sharing that example

**Comment by malikasinger1** [comment]
ohh so #147 is all about the same issue i'm facing, @matthewayne you should atleast refer me to to that issue, so irresponsible behaviour so disappointing behaviour buddy, 
thanks to @nathanjliu who refered me to that issue
