### ISSUE TITLE
Extending context by time

### ISSUE THREAD

**Issue by Fachastorm** [dialogflow/dialogflow-fulfillment-nodejs#155]
Hi guys, 

I'm trying to extend the time the context is up for since we are integrating our Dialogflow bot with Twilio. This is currently the code I have and it is saving contexts to firestore, but it overwrites it after 10 minutes when the user invokes the agent again. I'd like to be able to have someone text the bot and then even if they text it 20 minutes later, the bot will remember the current conversation. 

```
function writeToDb(agent){ 
    const session = agent.session
    const context = agent.contexts

    const dialogflowAgentRef = db.collection('contexts').doc(session);

    return db.runTransaction(t => {
      
      t.set(dialogflowAgentRef, {entry: context, merge: true});

      return Promise.resolve('Write complete');
    }).then(doc => {
      return console.log(`Wrote "${session}" to the Firestore database. ${doc}`);
      
    }).catch(err => {
      console.log(`Error writing to Firestore: ${err}`);
    });
  }


function readFromDb(agent) {
    const session = agent.session
    // const dialogflowAgentDoc = db.collection('dialogflow').doc(session);
    db.collection('contexts').doc(session)
    .get()
      .then(doc => {
  
        let contexts = doc.data()
        let contextsArray = contexts.entry
        
        contextsArray.forEach(context => { 
         agent.setContext(context)
 
    })
 
  })
    .catch(err => { 
      console.log(err) 
  })
  console.log(agent)
} 
```

It has been difficult to find ways around this using this library and I was wondering if anyone had any idea. Thanks a lot guys!

**Comment by sarahdwyer** [comment]
@Fachastorm 

Dialogflow contexts do indeed expire -- if you do need to extend contexts beyond what is currently supported, you might want to consider using [Actions on Google Node.js Client Lib](https://github.com/actions-on-google/actions-on-google-nodejs), which does let you use Dialogflow and have greater control over context lifespans. Also, if interested, Dialogflow has a [Firebase sample](https://github.com/dialogflow/fulfillment-firestore-nodejs).

**Comment by Fachastorm** [comment]
I went with the dialogflow node.js client library and was able to achieve what I was looking for. Thanks!

**Comment by divsbhalala** [comment]
Hello @Fachastorm 
I am trying to achieve the same but I am using their rest API endpoint but not sure how can I achieved that.

can you let me know when a node.js library that you used with the basic example?

Thanks in advance

**Comment by aleconwifi** [comment]
Hi @Fachastorm, can you send me your webhook code? Thanks.
