### ISSUE TITLE
Convert detect intent query result response to slack message

### ISSUE THREAD

**Issue by olegandreyev** [dialogflow/dialogflow-fulfillment-nodejs#164]
It there a way to convert response from intent api such below into prepared slack request body suitable for slack postMessage api?
```
"queryResult": {
    "fulfillmentMessages": [
      {
        "platform": "SLACK",
        "card": {
          "buttons": [
              ...
         ]
      }
```
So we have custom integration with slack by nodejs server. It means that server listens slack event by webhook. We use dialogflow api to detect intents then we use slack bot api to post message in channel. So now we manually parse response from Dialogflow api in `prepeareForSlackMessage` function and it's really painful. So It there another way to handle this case?
```
slackEvents.on('message', async event => {
  if (event.bot_id || (event.subtype && event.subtype === 'bot_message')) {
    return;
  }
  const responses = await dialogFlowClient.sendTextMessageToDialogFlow(event.text, event.channel);
  const response = responses[0];
  try {
    const { text, attachments } = prepareForSlackMessage(response);
    await slackApi.chat.postMessage({
      channel: event.channel,
      text,
      attachments
    });
  } catch (e) {
    console.log(e);
  }
});
```

**Comment by matthewayne** [comment]
This is a library to help with parsing webhook requests form Dialogflow not Slack.  If you already have a Slack integration you will need to port your Slack app to Dialogflow.
