### ISSUE TITLE
Have user Id's accessible in the agent

### ISSUE THREAD

**Issue by dadisigursveinn** [dialogflow/dialogflow-fulfillment-nodejs#176]
I want to get Id's of users interacting with my bot.

For example, to get the Id of the user interacting with the messenger platform I need to do this:
`agent.originalRequest.payload.data.sender.id`, 
but for slack I would need to do:
`agent.originalRequest.payload.data.user`.

But I would like to be able to do something like:
`agent.getRequestUserId()`

Is this feature something that could be implemented, or would it be too platform specific?

**Comment by matthewayne** [comment]
Sorry, I think this is too platform specific
