### ISSUE TITLE
add support for twilio messaging

### ISSUE THREAD

**Issue by malikasinger1** [dialogflow/dialogflow-fulfillment-nodejs#182]
twilio sms integration needs simple text response, when i do `agent.add("some response")` it works fine
but when i reply with rich response (which would not be displayed in sms of course) it simply doesnt even response and crash with error message:

```
Error: No responses defined for platform: twilio
    at WebhookClient.send_ (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:436:13)
    at promise.then (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:254:38)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

i think when request is comming from twilio you should simply cut rich response from the response object and should response with text only, with a warning message `warning: rich response would not be displayed in twilio messaging`

or as second option you may also draw a card in text messaging using ASCII emoji art (http://appcrawlr.com/ios/emoji-arts-text-arts-message-ar) 

if anyone have submitted pull request regarding please comment here

Thanks
Inzamam Malik

**Comment by nathanjliu** [comment]
You should be able to do this in your fulfilment code, by specifying supported platforms when sending a rich response.

```
// All platforms
const PLATFORMS = {
  UNSPECIFIED: 'PLATFORM_UNSPECIFIED',
  FACEBOOK: 'FACEBOOK',
  SLACK: 'SLACK',
  TELEGRAM: 'TELEGRAM',
  KIK: 'KIK',
  SKYPE: 'SKYPE',
  LINE: 'LINE',
  VIBER: 'VIBER',
  ACTIONS_ON_GOOGLE: 'ACTIONS_ON_GOOGLE',
};

// Platforms that support Rich messaging
const SUPPORTED_RICH_MESSAGE_PLATFORMS = [
  PLATFORMS.FACEBOOK,
  PLATFORMS.SLACK,
  PLATFORMS.TELEGRAM,
  PLATFORMS.KIK,
  PLATFORMS.SKYPE,
  PLATFORMS.LINE,
  PLATFORMS.VIBER,
  PLATFORMS.ACTIONS_ON_GOOGLE,
];
```

The simplest way of doing this would be something like: 

```
if(agent.requestSource === agent.ACTIONS_ON_GOOGLE) {
            agent.add(card);
        }
```

Twilio is not listed above, but you can check if a response has come from twilio like this:

```
if(agent.originalRequest.source === 'twilio') {
// request comes from Twilio
} else {
// request not from Twilio
}
```

**Comment by matthewayne** [comment]
This library is based off of how Dialogflow supports platforms.  This library only supports platforms that Dialogflow supports a visual editor for in Dialogflow's UI (Google Assistant, Facebook, Slack, Telegram, Kik and Viber). Any other platform can be supported using the method @nathanjliu details above and custom payloads

**Comment by MARCELNAKA** [comment]
@malikasinger1 , did you solve your problem? I'm facing the same error. Please share the solution.

thanks

**Comment by malikasinger1** [comment]
no my problem was not solved, however i did some ugly code to get myself out of trouble

```
export class BriefingActions {

static Briefing = async function (agent) {

        await http.get(baseUrl + '/vui/br', {
            EmployeeID: EmployeeID,
            OrganizationID: OrganizationID,
            myOpportunities: true
        }).then((speechOutput: any) => {

            console.log("speechOutput: ", speechOutput);
            agent.add(speechOutput.Text)
            if (agent.requestSource != "twilio") agent.add(new Card({
                title: 'Quota Briefing',
                imageUrl: speechOutput.ChartUrl,
                text: speechOutput.Text
            }));

        }).catch(e => {
            console.log("error: ", e);
            return agent.add("Sorry an error occured in api call")
        })
    }
}
```




```
import { raw } from './../../core'

export const webhook = functions.https.onRequest(async (request: Request, response: Response) => {
    try {

        raw.request = request; // preserving raw request for later use
        raw.response = response;

        const _agent = new WebhookClient({ request: request, response: response });
        console.log('Dialogflow Request headers: ' + JSON.stringify(request.headers));
        console.log('Dialogflow Request body: ' + JSON.stringify(request.body));


        const intentMap = new Map();

        intentMap.set(inputwelcome, welcomeActions.inputwelcome);
        intentMap.set(help, welcomeActions.help);
     
        intentMap.set(QuotaBriefing, BriefingActions.Briefing); // ok
      
        // intentMap.set('your intent name here', yourFunctionHandler);

        _agent.handleRequest(intentMap);

    } catch (e) {
        console.log("main error catch: ", e)
    }
})//end of webhook http trigger

```

**Comment by toniGallardo** [comment]
Hi everyone! 
I have the same problem! Did someone solve it?
I need to send some media files from dialogflow to Twilio for WhatsApp API and the platform it's getting me the same error

Thanks!

**Comment by alexedtionweb** [comment]
Hi toniGallardo I think would be better open another issue or pull request. I'm facing the same problem too.
To my bot work on Twilio Whatsapp I need to remove any media or rich response.
I think Twilio could provide any solution for that but looks like they want us to code the integration. If there it is no another solution please get in touch who wants to join forces and start to build the nodejs integration for Twilio Whatsapp.
What I see is that dialogflow receive photos as events. If it was at least url
