### ISSUE TITLE
`context.set` and `context.delete` with Node 8

### ISSUE THREAD

**Issue by sarupbanskota** [dialogflow/dialogflow-fulfillment-nodejs#183]
I make use of `async` / `await` quite heavily in my cloud function (node 8 based).

In order to use `context.set` and `context.delete`, I tried to upgrade to `0.6.1`, but I met with:

`error dialogflow-fulfillment@0.6.1: The engine "node" is incompatible with this module. Expected version "6".`

Any reason why Node 8 isn't supported?

**Comment by exs6350** [comment]
Make sure in your package.json to explicitly state your using node 8 by adding in: 
"engines": {
    "node": "8"
  }

**Comment by Vadorequest** [comment]
@sarupbanskota See https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/156

There is a workaround there, and explanation.
