### ISSUE TITLE
Dialogflow conversation - What is its usage?

### ISSUE THREAD

**Issue by Vadorequest** [dialogflow/dialogflow-fulfillment-nodejs#194]
I see the API has a `conversation` mode but I'm very much confused about it.
What does it do? Should I use it? In what case?

https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/3a849641108746eb95e84f71294c8a51befa18c6/src/dialogflow-fulfillment.js#L447-L465

I opened a SO question if you'd prefer to answer there:
https://stackoverflow.com/questions/53570585/what-is-a-dialogflow-conversation-usage-with-node-js-fulfillment-sdk

**Comment by KoffeeToKode** [comment]
Hello,
conv() is specific to Actions on Google library. In my opinion, you should only use it when you have no other choice. Doing so would help you add other integration such as Facebook in the future.

For instance, I use conv() for geolocalization data request specific to Google. If I add Facebook integration in the future, I would have to write some more code for geolocalization permission specific to Facebook.

On the other hand, if I only want to add text response that would always be the same no matter the integration (Google, Facebook, Slack, etc), then I would use `agent.add('my response');` from the Dialogflow library.
