### ISSUE TITLE
Text response is not adding to response when adding custom payload

### ISSUE THREAD

**Issue by GauravGaikwad94** [dialogflow/dialogflow-fulfillment-nodejs#202]
I am trying to add custom payload to response, but when I am adding payload to agent I am not able to get text response in fulfillment response.
fulfillment code:
```javascript
function welcome(agent) {
    agent.add("Welcome to my agent!");
    agent.add(new Payload("PLATFORM_UNSPECIFIED", {"key":"value"}));
}
```
fulfillment response:
```javascript
{
  "payload": {
    "null": {
      "key": "value"
    }
  },
  "outputContexts": []
}
```
and when I am not adding payload text response is coming
fulfillment code:
```javascript
function welcome(agent) {
    agent.add("Welcome to my agent!");
}
```
fulfillment response:
```javascript
{
  "fulfillmentText": "Welcome to my agent!",
  "outputContexts": []
}
```

**Comment by exs6350** [comment]
The fulfillment library expects either a rich response type message or an array of rich response messages. So if you wanted to add a text and payload add them to an array then call the add function

**Comment by GauravGaikwad94** [comment]
> The fulfillment library expects either a rich response type message or an array of rich response messages. So if you wanted to add a text and payload add them to an array then call the add function

Thank you @exs6350
