### ISSUE TITLE
Error when setup push notification using dialogflow-fulfillment-nodejs

### ISSUE THREAD

**Issue by philipskokoh** [dialogflow/dialogflow-fulfillment-nodejs#214]
I am following the guideline to opt-in user for push notification:
https://developers.google.com/actions/assistant/updates/notifications

I have done the console setup to enable the push notification on the intent (in this example it is 'send recommendation' intent). Then I create the setup push notification intent to opt-in user.
This 
```
    function setup_push(agent) {
        let conv = agent.conv();
        conv.ask(new UpdatePermission({intent: 'send recommendation'}));
        agent.add(conv);
    }
```
However I encounter an error at the `UpdatePermission({intent: 'send recommendation'})`. Here is the error message:
```
MalformedResponse
expected_inputs[0].possible_intents[0].input_value_data: The intent the app is asking for permission to send updates for is not found..
```

Any explanation regarding this error?

**Comment by sarahdwyer** [comment]
I think you meant to ask your question on the [Actions on Google client library](https://github.com/actions-on-google/actions-on-google-nodejs) Github.
