### ISSUE TITLE
Suggestion Title and Callback

### ISSUE THREAD

**Issue by adicuco** [dialogflow/dialogflow-fulfillment-nodejs#24]
Will it be possbile in the future to change the title of Suggestions for the platforms that require it (from "choose one item" to something custom) and, also, edit the callback of the replies?

**Comment by matthewayne** [comment]
I'm not sure what you're asking for here.  Can you open two new issues if these are still relevant(one for the Suggestion and another for callback?)  and provide additional information, examples and any relevant code?

**Comment by VinayakDeshpande11** [comment]
Hi @matthewayne 

even I was following this thread, the concern is when we use the fulfillment to show the Quick Replies, before showing the options the messenger sends "Choose an item", where as this can be replaced with the title while using UI to build the flow. Is it possible to replace the "Choose an item" text with a custom one?

TIA

**Comment by adicuco** [comment]
Sorry, I haven't seen the reply. As @VinayakDeshpande11 said, it would be very useful to be able to change the title of the quick replies when using fulfilment. Besides that, I believe that Suggestion lacks the option to define and change the payload for each quick reply.

**Comment by naranjja** [comment]
Hi, I am having the same issue. Looking to edit the "Choose an item" prompt.

Thanks!

**Comment by naranjja** [comment]
Hey guys, found a solution and posted it to #76. Hopefully it helps someone!
