### ISSUE TITLE
Disable DialogFlow Intent

### ISSUE THREAD

**Issue by iamrahulmaru** [dialogflow/dialogflow-fulfillment-nodejs#255]
Hello,
Is there any option to disable particular dialogflow intent?

I have one of my projects in Dialogflow with Actions on Google NodeJs. There are multiple intents in projects. Now I want to disable one intent (not delete)  but i can't find any option to disable it.
 is there any option or method for that?

**Comment by alexedtionweb** [comment]
In the dialogflow console you can open the intent and click on the blue dot (on the side of the name of the intent) and select ignore. 
https://cloud.google.com/dialogflow/docs/images/intents-priority.png

And the documentation about you can setup to a http request to manage intent (I think nobody uses that, the interface is enough but you can find in the GCP DOCS)

**Comment by iamrahulmaru** [comment]
@alexedtionweb thank you..
