### ISSUE TITLE
Dialogflow fulfillment is not working with Mongoose to connect to MongoDB

### ISSUE THREAD

**Issue by JeevaTM** [dialogflow/dialogflow-fulfillment-nodejs#268]
I wrote a basic function that connects to MongoDB using Mongoose, reads documents, and deployed the code in Cloud Functions. It responded correctly with the documents from MongoDB.

Code: 
```
var mongoose = require('mongoose');
var mongoDB = "mongodb://IP:port/db";
mongoose.connect(mongoDB, {
    useNewUrlParser: true
});
var db = mongoose.connection;
var Schema = mongoose.Schema;
var myCollection = new Schema({name: String,PO: String},{collections: 'myCollection'});
var myCollectionModel = mongoose.model('myCollection', myCollection, 'myCollection');

exports.helloWorld = (req, res) => {
  db.on('error', console.error.bind(console, 'connection error:'));
  myCollectionModel.find({name : "Jeeva"}, function(error, PO) {
      res.send(PO[0]);
  });
};

```

I wrote the code to accommodate in Dialogflow fulfillment in the following directions: When the intent is called, fetch the data, return it to the user.

Code:
```
'use strict';
const admin = require('firebase-admin');
const functions = require('firebase-functions');

const {WebhookClient} = require('dialogflow-fulfillment');
const {Card, Suggestion} = require('dialogflow-fulfillment');

var mongoose = require('mongoose');
var mongoDB = "mongodb://IP:Port/db";
mongoose.connect(mongoDB, {useNewUrlParser: true});
var db = mongoose.connection;
var db = mongoose.connection;
var Schema = mongoose.Schema;
var myCollection = new Schema({name: String,PO: String},{collections: 'myCollection'});
var myCollectionModel = mongoose.model('myCollection', myCollection, 'myCollection');

process.env.DEBUG = 'dialogflow:debug';
 
exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
  const agent = new WebhookClient({ request, response });
  console.log('Dialogflow Request headers: ' + JSON.stringify(request.headers));
  console.log('Dialogflow Request body: ' + JSON.stringify(request.body));
 
  function getData(name){
    var PO_number;
    myCollectionModel.find({name : "Jeeva"}, function(error, PO) {
      PO_number = PO[0].PO;
	});
    return PO_number;
  }
  
  function pending(agent){
    var name = agent.parameters.person;
    try{
      var PO_number = getData(name);
      agent.add(PO_number);
    }catch(error){
      agent.add(error.toString()); // Error: Unknown response type: "undefined"
    }
  }
    
  let intentMap = new Map();
  intentMap.set('pending-PO',pending);
  agent.handleRequest(intentMap);
});

```

It is not working. Does Dialogflow Fulfillment only support Firestore?

**Comment by alexedtionweb** [comment]
Hi this is not a Issue with dialogflow itself. You need to set promises to work with it. 
And the object db in this sample you just instantiate it twice 
var db = ...
You can use the firebase dialogflow as example on how's you promises should look like at dialogflow fullfitment objects.

**Comment by JeevaTM** [comment]
> Hi this is not a Issue with dialogflow itself. You need to set promises to work with it.
> And the object db in this sample you just instantiate it twice
> var db = ...
> You can use the firebase dialogflow as example on how's you promises should look like at dialogflow fullfitment objects.

Thank you for the information. 

Information I have gathered why it did not work and what changes has to be made in code:

- myCollectionModel.find() function runs asynchronously.
- Dialogflow library requires you to use JavaScript Promises if you're doing any asynchronous operation

```
function getData(name){
    var PO_number;
    return myCollectionModel.find({name : name}).exec()
      .then( doc => {
        return Promise.resolve(doc[0].PO);
      });
  }

  function pending(agent){
    var name = agent.parameters.person;
    return getData(name)
      .then( PO_number => {
      	agent.add(name + ", approval pending for following PO");
        agent.add( PO_number );
      })
      .catch( error => {
        agent.add("There no pending PO for approval, " + name + ".");
      });
  }
```

**Comment by cristiaan05** [comment]
Can I use mysql to connect to dialogflow fulfillment?

**Comment by JeevaTM** [comment]
@cristiaan05 Yes, you can. There is a module for mysql in NodeJS. [Tutorial](https://www.w3schools.com/nodejs/nodejs_mysql.asp)

Remember JS is asynchronous so you have to use the same method as I did.

**Comment by cristiaan05** [comment]
I already did this buy i don't know how proof if it is connected or not
