### ISSUE TITLE
Version v0.3.0-beta.3 is not available when installing via NPM

### ISSUE THREAD

**Issue by tejashah88** [dialogflow/dialogflow-fulfillment-nodejs#40]
I was trying to figure out why the `originalRequest` field wasn't showing up for the longest time, and it turns out that I was using the `v0.3.0-beta.2` version, when in fact, accessing the original request is in `v0.3.0-beta.3`. On the [NPM website](https://www.npmjs.com/package/dialogflow-fulfillment), it shows that beta.2 is the latest version although #14 seems to suggest that beta.3 was released a while back, and the documentation shows that you can access the original request. It would be nice to be able to install this package without specifying the version number every time, since it's not obvious that just running `npm install dialogflow-fulfillment` will not install the latest version.

Here's the installation logs:
![image](https://user-images.githubusercontent.com/11187343/39403188-6ade698a-4b42-11e8-9bbb-ef9ecb43eaac.png)

**Comment by matthewayne** [comment]
This has been fixed in v0.4.1
