### ISSUE TITLE
`,` instead of `;` on constant declaration

### ISSUE THREAD

**Issue by jamescoggan** [dialogflow/dialogflow-fulfillment-nodejs#41]
The end of line should be a `;` not `,` 

https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/40c8a456569e1b2950f43e9064a1aed17afc835c/samples/actions-on-google/functions/index.js#L27

**Comment by matthewayne** [comment]
This was fixed.  Thanks for reporting!
