### ISSUE TITLE
Sample Produces error:  MalformedResponse expected_inputs[0].input_prompt.rich_initial_prompt: 'item[1]' must not be empty.

### ISSUE THREAD

**Issue by sherazlodhi** [dialogflow/dialogflow-fulfillment-nodejs#47]
If you follow the steps [here ](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/tree/master/samples/actions-on-google
) (Option 2) and run the application in simulator you get the error below

MalformedResponse
expected_inputs[0].input_prompt.rich_initial_prompt: 'item[1]' must not be empty.

Edit: Option 1 to option 2

**Comment by omfd** [comment]
@sherazlodhi were you able to solve the issue ?? because I am facing the same issue

**Comment by sherazlodhi** [comment]
@omfd  can you post your code?

**Comment by sherazlodhi** [comment]
Option 1 has now been changed to option 2 on that link.

**Comment by SiddAjmera** [comment]
I'm still facing the issue. I've used the same code that's provided in the sample [here](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/master/samples/actions-on-google/functions/index.js)

@sherazlodhi , @omfd , was anyone of you able to fix the issue?

**Comment by SiddAjmera** [comment]
@matthewayne , I think there is definitely an issue either with [this Actions On Google Sample](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/master/samples/actions-on-google/functions/index.js), or with the `agent.conv` method.

**Comment by amitdesh** [comment]
I still see the issue as well.

**Comment by matthewayne** [comment]
This was fixed in v0.4.1
