### ISSUE TITLE
is this library is owned by google/dialogflow?

### ISSUE THREAD

**Issue by malikasinger1** [dialogflow/dialogflow-fulfillment-nodejs#49]
I'm a chatbot develoepr and working with dialogflow from last 1 year, today i got some time to get into dialogflow v2 and found this library, so my questoion is is this library is official or third party?

i got this question because there are several approach for making fulfilment webhook: 

1) JOSN request/response approach
2) https://github.com/actions-on-google/actions-on-google-nodejs
3) https://github.com/dialogflow/dialogflow-fulfillment-nodejs

should i learn to use all of them, can anyone please do a comparison of these libraries? whihc one of them will get longer and stable support

**Comment by WilhelmErasmus** [comment]
I would recommend not trying this. The docs aren't detailed at all and things don't seem consistent. I think I'm going to try the JSON request/response instead. (I spent 4+ hours yesterday trying to get parameter values inside my intent fulfiller.)

**Comment by malikasinger1** [comment]
nice, now i understand this is owned by google and dialogflow, 
but it is still in beta and right now it is not stable enough to adopt,
can any one please tell me the release date?

**Comment by matthewayne** [comment]
This is an official Dialogflow library and Dialogflow is owned by Google.

If you're starting out with Node.js Dialogflow fulfillment and are interested in multiple integrations or aren't sure what integration you plan on using this library is the best place to start

If you're using Node.js Dialogflow fulfillment and are only interested in the Actions on Google integration the actions-on-google npm module is the the best place to start

If you're interested in Dialogflow or Actions on Google development on non-Node.js platforms JSON requests/responses are your best bet.
