### ISSUE TITLE
Card not supporting multiple buttons

### ISSUE THREAD

**Issue by Mrinnaal** [dialogflow/dialogflow-fulfillment-nodejs#62]
Cards are not supporting multiple buttons! Why is it so? Or is there any way to add more than one button in card? Please let me know ASAP. Even if i send it as payload same issue! Check with that and let us know.

**Comment by scolinas** [comment]
Hi, same issue here. Cards only support one button

**Comment by matthewayne** [comment]
Please see issue #34 for context.  Multiple buttons are not supported.  See the documentation for the platform you're working with for info on how to add multiple buttons with a Payload

**Comment by fabio-C** [comment]
Created this. It is ok if you are using only Facebook platform.
https://github.com/fabio-C/dialogflow-fulfillment-nodejs
