### ISSUE TITLE
Actions on google dependency

### ISSUE THREAD

**Issue by aringlot** [dialogflow/dialogflow-fulfillment-nodejs#65]
Dear colleagues, 

I tried to develop a fulfillment for Google assistant and none of examples where working.
To host my application I use self hosted server on express.js. 

There was a couple of strange error responses from google assistant device simulator.
I spent a couple of days investigating the issue and here are the results:
- my issue is probably related to [59](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/59)
- I have temporary replaced WebhookClient with dialogflow from Actions-on-goolge package

To make everything work version of Actions-on-goolge I am using is 2.1.2

**Comment by matthewayne** [comment]
This should be fixed in v0.4.1.  Can you update and try it again?

**Comment by matthewayne** [comment]
Closing for now, please reopen if you have an issue after updating to v0.4.1

**Comment by DenisBogatirov** [comment]
Still have an error, version 0.4.1

**Comment by jorgecasar** [comment]
I'm having the same issue with version ^0.4.1

Any update?

**Comment by loltag22** [comment]
Same error here, I tried everything. Version 0.4.1

**Comment by sardarbavneetsingh** [comment]
I am making self hosted fulfillment with actions sdk, I am using heroku to deploy my fulfillment functions, but can figure out how to code the fulfilment and what is the structure of data that i will receive from request from actions and i am may sound confusing, but I guess i am lost so I am trying to state my position here. If anyone can get me on track. Also the documentation doesn't cover the topic. I have done my research on internet...
