### ISSUE TITLE
Sample for Basic Fulfillment and Conversation Setup in docs

### ISSUE THREAD

**Issue by xRahul** [dialogflow/dialogflow-fulfillment-nodejs#66]
The [Basic Fulfillment and Conversation Setup Doc](https://dialogflow.com/docs/getting-started/basic-fulfillment-conversation) does not use dialogflow-fulfillment-nodejs in its example. I have  created a sample for the **weather api example** that uses `dialogflow-fulfillment`.

This sample's features:
* Fully 3rd party (doesn't require firebase use)
* Uses Express server
* Can add readme to show use with ngrok
* It also contains a 3rd party api call which is missing from the rest of the examples.

Ask: Can I add the sample here in the samples folder or if not possible I can push that to my repo and add a link here.

**Comment by McGern** [comment]
Hi,

Not an answer sorry. Does your example include slot filling using a webhook?

J

**Comment by xRahul** [comment]
No. I've yet to understand what that is. I haven't been able to find that in the guides.

**Comment by matthewayne** [comment]
We're updating the getting started guide to use the dialogflow-fulfillment library.  Stay tuned!
