### ISSUE TITLE
Multi lang not working

### ISSUE THREAD

**Issue by Ashwin-Kapes** [dialogflow/dialogflow-fulfillment-nodejs#69]
I've added two languages for my agent i.e "en" & "hi".

When user types in English then **en Agent** must be executed.
When user types in Hindi then **hi Agent** must be executed.

But everytime only **en Agent** get's executed.
On Firebase console I see **Request locale: en**. Why I'm not receiving **hi** locale even if user types in Hindi(hi) lang.
How to trigger different locales of same Agent?
How dialogflow understands which locale to post to Firebase functions.

**Comment by matthewayne** [comment]
When testing in the Dialogflow simulator, you can only test the selected language for the agent. For example it sounds like English is your currently selected language. If you need to test in other languages, click on the corresponding language chip (e.g. hi) in the upper left of the DIalogflow console to switch languages.

Relevant docs page: https://dialogflow.com/docs/multi-language#testing_languages_in_the_console

**Comment by Ashwin-Kapes** [comment]
The above solution is only successful when I'm testing from Dialogflow. When conversation channel is Facebook, Dialogflow doesn't detect users language.

So if user types in English(Using messenger) then Dialogflow must reply in English and if user types in Hindi(Using messenger) then Dialogflow must reply in Hindi. But in whichever lang user is typing DF response is in English only. Is Detect Intent API useful in this case?

**Comment by ashishthakre** [comment]
yes , we are not getting other languages is not detect

**Comment by SteLom** [comment]
Hello,
I'm experiencing the same issue. When a request is coming from facebook messenger, dialogflow is not able to recognize the intent. when the same phrase is going through the console, intent (and language too) is well recognized.

thanks for your help
S

**Comment by Ashwin-Kapes** [comment]
I guess Intent detection is only for Google Assistant for now.

**Comment by manureddykalluru** [comment]
is there any way we can send language as an input using speech recognition in dialogflow like
to continue in english say english and to continue in danish say danish

**Comment by madanmeena** [comment]
> The above solution is only successful when I'm testing from Dialogflow. When conversation channel is Facebook, Dialogflow doesn't detect users language.
> 
> So if user types in English(Using messenger) then Dialogflow must reply in English and if user types in Hindi(Using messenger) then Dialogflow must reply in Hindi. But in whichever lang user is typing DF response is in English only. Is Detect Intent API useful in this case?

I am facing the exact same issue, does it have a solution?
I inspected the raw interaction log and the languageCode is always the default language of Dialogflow even though the Facebook account I am using has a different language.

Where can i raise this issue?

**Comment by Rufus13apostol** [comment]
I there, I contacted the Dialogflow support team and they told me the following:

"_At the moment, Dialogflow does not yet support multiple languages for any of its built-in integrations - so requests from Facebook Messenger will automatically only be sent to the Default Language of the agent.

However, you can try to make your own implementation for this. You may consider creating a middleware that would serve as a bridge between your Dialogflow agent and your Facebook Messenger bot. 

When a user sends a query from Facebook Messenger, your middleware should detect which language was used and then it should send a detectIntent request (https://cloud.google.com/dialogflow/docs/reference/rest/v2/projects.agent.sessions/detectIntent ) to Dialogflow containing both the query and a "languageCode" parameter field with the language tag (https://cloud.google.com/dialogflow/docs/reference/language ) of the end-user's language.
You can use Dialogflow's REST API (https://cloud.google.com/dialogflow/docs/reference/rest/v2-overview ) or client libraries (https://cloud.google.com/dialogflow/docs/reference/libraries/overview ) to integrate your middleware to Dialogflow._"

So, I guess it should be a handmade solution for now...
