### ISSUE TITLE
Set context after button push for facebook webview

### ISSUE THREAD

**Issue by McGern** [dialogflow/dialogflow-fulfillment-nodejs#70]
Hi,

Really struggling here to find the correct (or any) solution, so any help would be appreciated.

I am using messenger as my interface. I am creating a prototype where I have a scenario where
- the user is presented with a carousel of movies (for example) each with a button "Choose viewing times"
- This button will open a url (using webview) with the movie id in the querystring.
- The webview opens with a list of days and times, and the user selects one
- An api call is made and a response is created (using facebook send api) to display the message "you selected Tuesday 7pm" and a set of options about whether the user is happy with their selection "yes,no,choose again"

I have this working visually, but not with actual data passing around. There are a bunch of questions I have around this:-

1) I would rather use my "agent" to do the message handling rather than shoehorning messages via the facebook graph api, but once I leave the ecosystem of the agent and open the webview I don't know how to get a handle on the agent to jump back into the conversation.
2) How can I set a context when the button to open the webview is clicked so when they come back, the yes/no options are in context for this "select movie" intent - as well as having the values in context in case they don't use the buttons

Again, any assistance would be helpful. I think this is a bit too new for stackoverflow given the lack of Q/A there.

Cheers,
Jarrod

**Comment by matthewayne** [comment]
Hi Jarrod, sorry you're having trouble. I don't think this is the right venue for the question as it doesn't relate to the fulfillment library and isn't very visible to others that might be having similar issues.  Here is a StackOverflow question and answer you might find useful: https://stackoverflow.com/questions/50864959/passing-facebook-messenger-bot-webview-data-to-dialogflow-and-continuing-the-con/50864994#50864994
