### ISSUE TITLE
how to remove "Choose an item" text before suggestion

### ISSUE THREAD

**Issue by magnum** [dialogflow/dialogflow-fulfillment-nodejs#76]
Anytime I add Suggestion to agent, on facebook there's always a text added saying "Choose an item"
how can it be removed or translated?

**Comment by naranjja** [comment]
Same here, how do we change this?

**Comment by naranjja** [comment]
In case anyone's interested, here's my [fork](https://github.com/naranjja/dialogflow-fulfillment-nodejs) and [the complete edited file](https://github.com/naranjja/dialogflow-fulfillment-nodejs/blob/master/src/rich-responses/suggestions-response.js).

**Comment by pranavgor** [comment]
hey @naranjja I made the changes in the respective folder (suggestions-response,js) but for some reasons those changes are not being reflected, is there anything more than just saving the file that I need to do ?

**Comment by pranavgor** [comment]
I installed your github module itself, it works perfectly. Thanks @naranjja

**Comment by TexugoGaio** [comment]
hey guys, I'm new to this platform, how do I use this @naranjja code in my project? How would they require them?

**Comment by naranjja** [comment]
@TexugoGaio In your project's package.json file, you would edit the version of "dialogflow-fulfillment" to the URL of my repo. Like this:

"dialogflow-fulfillment": "git+https://github.com/naranjja/dialogflow-fulfillment-nodejs.git"

**Comment by matthewayne** [comment]
Since this is a platform specific feature, it won't be supported in the library.  If you'd like to use platform-specific responses, I'd recommend using the [payload response type](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/master/docs/Payload.md)

**Comment by petept** [comment]
@matthewayne Appreciate the great library, cheers for the great work. The issue with a quick reply payload is the limitation of not being able to send fulfilment messages along with a custom payload. The solution above supplied by @naranjja is a good work around until this functionality is added. There is a pull request pending that elevates this limitation. (#113) Any chance of getting this merge any time soon? Would be very useful for my current use case. Cheers.

**Comment by Vadorequest** [comment]
@matthewayne I understand what you're saying and the design choice. But the reality of this choice push developers to fork and use their own implementation of your library, which is really not a good thing.

Stepping back a bit, and after using this lib for 2 days, I can tell a proper abstraction of the specificities of each Platform is a must-have. For instance, in my case I need to deal with both Facebook and Web integrations, and I ended up writing wrappers around basic stuff like Text or Suggestion.

If you don't want to write custom integration code in this library, so be it. What do you think about writing a wrapper of your own library, or a bunch of helpers to deal with each platform specificities? It's something the community will need on the long-run.

Also, your link to payload response type is dead.

**Comment by magnum** [comment]
i solved using a custom payload ad @matthewayne suggested: this way no fork is needed /cc @Vadorequest i'm using somthigng like this

`sendOptions(agent, options) {
    agent.add("please choose an item...")
    options.map(option => agent.add(new Suggestion(option)))
    let payload = new Payload(agent.FACEBOOK, {
      text: introText,
      quick_replies: options
        .slice(0, 5)
        .map(option => {
        return {
          content_type: "text",
          title: option,
          payload: option
        }
      })
    });
    agent.add(payload)
  }`

**Comment by Vadorequest** [comment]
@magnum I don't understand why you send `agent.add("please choose an item...")` if you don't actually want it to be displayed. But I'm not so used to Dialogflow, getting started.

**Comment by magnum** [comment]
> @magnum I don't understand why you send `agent.add("please choose an item...")` if you don't actually want it to be displayed. But I'm not so used to Dialogflow, getting started.

just saying this way you can customize it, for example translate it (that was my need) or for example not use it.

**Comment by jbonet** [comment]
How would this work for Telegram?

**Comment by Parau** [comment]
> i solved using a custom payload as @matthewayne suggested: this way no fork is needed /cc @Vadorequest i'm using somthing like this
> 
> ```
> sendOptions(agent, options) {
>     agent.add("please choose an item...")
>     options.map(option => agent.add(new Suggestion(option)))
>     let payload = new Payload(agent.FACEBOOK, {
>       text: introText,
>       quick_replies: options
>         .slice(0, 5)
>         .map(option => {
>         return {
>           content_type: "text",
>           title: option,
>           payload: option
>         }
>       })
>     });
>     agent.add(payload)
>   }
> ```
Tried this code but it worked only in the Dialogflow simulator not inside Facebook messenger...

**Comment by madhavaspect** [comment]
let payload = new Payload(agent.FACEBOOK, {
      text: introText,
      quick_replies: options
        .slice(0, 5)
        .map(option => {
        return {
          content_type: "text",
          title: option,
          payload: option
        }
      })
    });
    agent.add(payload)

That works for me in the FB messenger as well.

**Comment by rebuby9090** [comment]
> @TexugoGaio In your project's `package.json` file, you would edit the version of `"dialogflow-fulfillment"` to the URL of my repo. Like this:
> 
> ```json
> {
> "dialogflow-fulfillment": "git+https://github.com/naranjja/dialogflow-fulfillment-nodejs.git"
> }
> ```

what is dialogflow-fulfillment version which you editted?
It's 0.6.1 or lower?

**Comment by rebuby9090** [comment]
> So, what I did was go into `/src/rich-responses/suggestions-response.js` and modified the Suggestion constructor to include `this.title` besides `this.replies`:
> 
> ```js
> constructor(suggestion) {
>     super();
>     this.platform = undefined;
>     this.replies = []; 
>     this.title = "Choose an item:"
> ```
> 
> Then, I set the value of `this.title` to the passed in value to the suggestion object:
> 
> ```js
> } else if (typeof suggestion === 'object') {
>     this.replies.push(suggestion.reply)
>     this.title = suggestion.title
> ```
> 
> Lastly, I modified the `getV2ResponseObject_()` function so that it handles `this.title` for the Facebook response:
> 
> ```js
> } else if (platform === PLATFORMS.FACEBOOK) {
>     response = {
>         quickReplies: {
>             title: this.title,
>             quickReplies: this.replies
>         }
>     }
> }
> ```
> 
> Once that's done, you can make quick replies like this. First, make the first one with a title:
> 
> ```js
> const quickReplies = new Suggestion({
>     title: "My custom message",
>     reply: "Option 1"
> })
> ```
> 
> And then add the rest of the options like so:
> 
> ```js
> quickReplies.addReply_("Option 2")
> quickReplies.addReply_("Option 3")
> quickReplies.addReply_("Option 4")
> ```
> 
> Lastly,
> 
> ```js
> agent.add(quickReplies)
> ```
> 
> And it works!

what is dialogflow-fulfillment version which you editted?
It's 0.6.1 or lower?
