### ISSUE TITLE
dialogflow-fulfillment to support on Alexa intents?

### ISSUE THREAD

**Issue by anmolagar** [dialogflow/dialogflow-fulfillment-nodejs#78]
What is the best way to support fulfilment created from dialogflow-fulfillment to support on Alexa intents?

Any samples or pointers appreciated.

Please note: Alexa has moved on and dialogflow import export feature is not compatible with the current alexa skills version.

**Comment by sarahdwyer** [comment]
Have you seen this? https://github.com/dialogflow/fulfillment-importer-nodejs

**Comment by matthewayne** [comment]
Dialogflow's existing import/export feature requires a separate fulfillment backend for Alexa and will not be supported by this library.
