### ISSUE TITLE
WebhookClient.handleRequest() doesn't accept Map()

### ISSUE THREAD

**Issue by michaelachmann** [dialogflow/dialogflow-fulfillment-nodejs#80]
Our team has been trying to pass a map of name and handler for our intents / actions to `WebhookClient().handleRequest`:
```
    const agent = new WebhookClient({ request, response });  
    
      // Array of all actions.
    const actions: = [
     DemoAction,
    // Add actions here.
    ];
    
    // Actions are added to intentMap, thereafter to handleRequest for routing.
    let intentMap = new Map();
    actions.forEach(action => intentMap.set(action.name, action.handler));
    
    // Run the proper function handler based on the matched Dialogflow intent name  
    agent.handleRequest(intentMap);
```
Actions look like this:
```
    export const name = 'demo_action';
    export function handler(app) {
        const paramNumber = parseInt(app.parameters['number'].toString());
        app.add(`I incremented your number. Here you go: ${paramNumber + 1}`);
    }
```
This however results in the error `handleRequest must contain a map of Dialogflow intent names to function handlers`. Now the map of intent names to function handlers is exactly what we've included in intentMap. For testing purposes we changed the lines  lines 244-248 `/dialogflow-lambda-fulfillment/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js` to:
```
    if ((handler instanceof Map)) {
          return Promise.reject( new Error(
            'handleRequest must contain a map of Dialogflow intent names to function handlers'
          ));
        }
```
This defeats, of course, the whole purpose of this type check since the original line was if `(!(handler instanceof Map))`. On the other hand, the Map which we pass to `WebhookClient().handleRequest` works perfectly well with our modification. It's also strange that `(intentMap instanceof Map)` is `true` if we check it in our project, but apparently turns into `false` once it's passed to handleRequest().

Are there any ideas, where this error might be coming from and how to solve it?

**Comment by abhi007tyagi** [comment]
```
function welcome (agent) {
    agent.add(`Welcome to Express.JS webhook!`);
}

function fallback (agent) {
    // console.info(`unknown -- ${agent.originalRequest}`);
    agent.add(`I didn't understand`);
    agent.add(`I'm sorry, can you try again?`);
}

function WebhookProcessing(req, res) {
    const agent = new WebhookClient({request: req, response: res});
    console.info(`agent set`);

    let intentMap = new Map();
    intentMap.set('Default Welcome Intent', welcome);
    intentMap.set('Default Fallback Intent', fallback);
// intentMap.set('<INTENT_NAME_HERE>', yourFunctionHandler);
    agent.handleRequest(intentMap);
}
```
This is how I did.  You can check the complete code in the current [Pull Request](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/pull/81) #81.

**Comment by michaelachmann** [comment]
@abhi007tyagi We're basically doing the same thing in a different way. We use an Array, the forEach-function iterates through the elements and 'sets' them to the intentMap.

**Comment by abhi007tyagi** [comment]
Check the intent name that is getting saved in the MAP.

**Comment by matthewayne** [comment]
Are you trying to fulfill all intents with the same function?  If so you can pass a function to the `agent.handleRequest` method that will be called no matter what intent is match in Dialogflow.  Here is an example:

```
const agent = new WebhookClient({ request, response });  
function handler(agent) {
    const paramNumber = parseInt(agent.parameters['number'].toString());
    agent.add(`I incremented your number. Here you go: ${paramNumber + 1}`);
}

agent.handleRequest(handler);
```

Keep in mind that if the above is what you want to do, every intent that uses fulfillment in you Dialogflow agent has to have a required number parameter, otherwise the number might not be sent to the webhook and could result in a error in your fulfillment.
