### ISSUE TITLE
No matching version found for dialogflow-fulfillment@^1.0.0

### ISSUE THREAD

**Issue by PotassiumK** [dialogflow/dialogflow-fulfillment-nodejs#83]
Following the current documentation, I added `"dialogflow-fulfillment": "^1.0.0"` to my dependencies in `package.json`.

Unfortunately, when running `npm install`, the 1.0.0 version was not found.
My project uses a Dialogflow v2 agent, what is the correct version I should be replacing `^1.0.0` with?

**Comment by PotassiumK** [comment]
I changed it to `^0.4.1` for now. My question still holds though, is there a reason it says ^1.0.0 in the documentation?

**Comment by abhi007tyagi** [comment]
TestAgent_V2 abhinavtyagi$ sudo npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for dialogflow-fulfillment@^1.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'Test_Agent'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abhinavtyagi/.npm/_logs/2018-07-07T12_58_15_852Z-debug.log

**Comment by sarahdwyer** [comment]
Can you include the link to the docs where you saw this?

**Comment by schrom** [comment]
It's right here on the start page of the project

https://github.com/dialogflow/dialogflow-fulfillment-nodejs

![grafik](https://user-images.githubusercontent.com/6514317/42715025-6e1ffcdc-86f5-11e8-9346-2f5ef23829eb.png)

**Comment by matthewayne** [comment]
This has been fixed in the latest version.  Thanks for reporting!
