### ISSUE TITLE
what is the plan for release this library?

### ISSUE THREAD

**Issue by malikasinger1** [dialogflow/dialogflow-fulfillment-nodejs#85]
I'm wondering this repo didn't not get any update/commit from a month, last commit is 27 day ago right now

what is your roadmap? any plan to release? it is critical for me if you are not planning to release soon please let me know

**Comment by malikasinger1** [comment]
any update?

**Comment by malikasinger1** [comment]
hey @sarahdwyer why did you closed this issue without answering i was wondering

**Comment by lucaswadedavis** [comment]
@malikasinger1 this library is actively maintained, but we don't normally publicize our release schedule.
