### ISSUE TITLE
Send dynamic data in response using agent.add()

### ISSUE THREAD

**Issue by karthikprabhun** [dialogflow/dialogflow-fulfillment-nodejs#91]
Hello All,

Is it possible to send dynamic data with response which we got that from backend api ? There are cases where we need to send real time data to dialogflow agent ( in turn to client) by calling a API . I tried below code to implement this but seems like not working , here " value" is the data that we are getting from api response and the same has been parsed / navigated to extract value.

agent.add(`stock price is ` + JSON.parse(value).IRXML.StockQuotes.Stock_Quote[0].Trade)

Prior above code execution , i'm making a synchronous external API call using promotion so that the result is replaced in the agent.add section. 

At present, i'm not able to execute agent.add function inside promotion then  function. Could you please assist me here.

Let me know for more information required.

Thanks,
Karthik

**Comment by matthewayne** [comment]
You'll need to wrap your async call in a promise and return the promise in the handler function as seen in this example: https://github.com/dialogflow/fulfillment-bike-shop-nodejs/blob/master/functions/index.js#L61

If you don't return a promise in the handler function the function will return without having added any responses.
