### ISSUE TITLE
Cannot read property 'length' of undefined at V2Agent.convertV2ContextToV1Context_

### ISSUE THREAD

**Issue by pranigit13** [dialogflow/dialogflow-fulfillment-nodejs#92]

**Comment by matthewayne** [comment]
Please open a new issue and provide your code and/or any error messages

**Comment by ptrckbp** [comment]
Got this error and figured out what went wrong. Hopefully, this will help someone! 

In Dialogflow, when you go to "Diagnostic Info", then "Fulfilment request", then click "Copy Raw Response", it's not copying the fulfillment request, and if you use this for testing, the format is wrong, yielding this error! If you want to test locally you should copy the text field manually.
