### ISSUE TITLE
Payload not add to response

### ISSUE THREAD

**Issue by katopz** [dialogflow/dialogflow-fulfillment-nodejs#93]
I replace
https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/master/samples/actions-on-google/functions/index.js#L74-L87

With
```js
  function other (agent) {
    const facebookPayload = {
      attachment: {
        type: 'template',
        payload: {
          template_type: 'generic',
          elements: [
            {
              title: 'Title: this is a title',
              image_url: `https://assistant.google.com/static/images/molecule/\
    Molecule-Formation-stop.png`,
              subtitle: 'This is a subtitle',
              default_action: {
                type: 'web_url',
                url: 'https://assistant.google.com/'
              },
              buttons: [
                {
                  type: 'web_url',
                  url: 'https://assistant.google.com/',
                  title: 'This is a button'
                }
              ]
            }
          ]
        }
      }
    }

    agent.add(new Payload(agent.FACEBOOK, facebookPayload))
  }
```

I expect response to have payload, but I got this response instead
```json
{
  "fulfillmentMessages": [],
  "outputContexts": []
}
```

BTW It work with `Card` example but not payload, any hint?

**Comment by katopz** [comment]
Oh, I just realize that I need to use Facebook to get the payload, tested on DialogFlow won't show any.

**Comment by robertrita** [comment]
@katopz I have the same issue. You mean just because it's FACEBOOK payload it won't show on DIAGNOSTIC INFO json? I also tried using postman but still blank fulfillmentMessages. Where can I check it without going to facebook?

**Comment by sarahdwyer** [comment]
The request needs to come from the platform (FB, Slack, etc) in order for the payload to appear

**Comment by mgarod3** [comment]
I'm trying the same code as @katopz making the request from Facebook and it's not working. I do not receive any answer. I've also tried with agent.add(new Card()) instead of payload but it's not working neither.
