### ISSUE TITLE
Timeout or reason why response isn't sent from async function?

### ISSUE THREAD

**Issue by stevejcox** [dialogflow/dialogflow-fulfillment-nodejs#95]
When using a promise agent.add doesn't ever send a response to the user.

Is there a maximum time period for the response to send or any other reason why it wouldn't send?

**Comment by stevejcox** [comment]
Looks like there’s a 3 second timeout for some integrations, slack being one. So anything that takes longer than 3 seconds will silently fail.

With functions and the potential for a cold start, this gives *very* little time for any asynch responses.

Is there any way to send to a channel / dm without it explicitly being a response?

**Comment by matthewayne** [comment]
Can you provide your code and/or and error messages?

**Comment by matthewayne** [comment]
Dialogflow webhooks need to response [within 5 seconds](https://dialogflow.com/docs/fulfillment#limits) or Dialogflow considers the fulfillment to have timed out and the response defined in Dialogflow's console will be surfaced (if present).  Looks like your code might be running into that limit

**Comment by stevejcox** [comment]
Yes, it seems cloud functions are not a good place for this, knowing that cold start time can be several seconds and a timeout that short gives the system very little time to do anything.
