### ISSUE TITLE
Blank "fulfillmentMessages" when trying to create a dynamic Facebook Messenger Payload

### ISSUE THREAD

**Issue by robertrita** [dialogflow/dialogflow-fulfillment-nodejs#97]
Blank "fulfillmentMessages" when trying to create a dynamic Facebook Messenger Payload. Text and Suggestions works pretty well.

{
  "fulfillmentMessages": [],
  "outputContexts": []
}
-----------------------------------------------------------------
I'm using "Temperature trivia" template from here: https://dialogflow.com/docs/examples

here is my Payload:

    const facebookPayload = {
      attachment: {
        type: 'template',
        payload: {
          template_type: 'generic',
          elements: [
            {
              title: 'Title: this is a title',
              image_url: 'https://assistant.google.com/static/images/molecule/Molecule-Formation-stop.png',
              subtitle: 'This is a subtitle',
              default_action: {
                type: 'web_url',
                url: 'https://assistant.google.com/',
              },
              buttons: [
                {
                  type: 'web_url',
                  url: 'https://assistant.google.com/',
                  title: 'This is a button',
                },
              ],
            },
          ],
        },
      },
    };

    agent.add(new Payload(agent.FACEBOOK, facebookPayload));

**Comment by sarahdwyer** [comment]
The request needs to come from the platform (FB, Slack, etc) in order for the payload to appear

**Comment by robertrita** [comment]
i see.. this won't apply on my use case. thank you.
