### ISSUE TITLE
Basic asynchronous functionality breaking

### ISSUE THREAD

**Issue by kylebegovich** [dialogflow/dialogflow-fulfillment-nodejs#98]
Addendum to issue #94, as there is no dependency on lambda breaking the asynchronous callback structure in the code.

Dialogflowseems to be failing to follow the async flow of the most basic example I could produce:
<img width="437" alt="screen shot 2018-07-16 at 5 45 14 pm" src="https://user-images.githubusercontent.com/21372311/42787443-24bbc3b4-8920-11e8-9db6-7d24761e5f08.png">
This code has some log statements and sets some setTimeout calls to add a response to the agent after 5 seconds. after 10 seconds, another setTimeout will log some output.

The invocation looks like so: _note the 'Not available'_
<img width="362" alt="screen shot 2018-07-16 at 5 49 09 pm" src="https://user-images.githubusercontent.com/21372311/42787567-a216046e-8920-11e8-9f5e-39213ba112ae.png">

And the logs look like so:
<img width="1029" alt="screen shot 2018-07-16 at pm" src="https://user-images.githubusercontent.com/21372311/42787736-718270de-8921-11e8-8e43-dba18c6324b0.png">

Note here that the most recent response is at the top, and that "Function execution took X ms, finished with status code: Y" is before the setTimeout functions return. The effect of this is that long calls (such as pinging API endpoints), will not have their values returned by the time the agent closes. This contradicts my basic understanding that execution is not yielded until all promises have been resolved in the function.

Any and all help would be appreciated

**Comment by kylebegovich** [comment]
It turns out there's a workaround to this, where you wrap the entire function in a promise if you have any async calls, like so:
<img width="442" alt="screen shot 2018-07-17 at 4 25 02 pm" src="https://user-images.githubusercontent.com/21372311/42846434-90976890-89de-11e8-982e-c41f3e99d276.png">

I believe the initial issue still stands, as the function shouldn't yield. But for other developers looking to just have a working solution now, do something like the above

**Comment by matthewayne** [comment]
JavaScript is asynchronous and a promise needs to be returned by the handler function in order for statements that alter the response to affect the response. 

In your first code snippet the function is implicitly returned before the statements in the setTimeout blocks are executed.  Since the function has finished executed the library then takes any responses added (in your case no responses were added) and responds to the Dialogflow webhook request.  By the time the agent.add(...) statement is run the response has already been sent to Dialogflow without the response.  Returning a promise for any async operations is the intended design.

**Comment by amadeuspzs** [comment]
> It turns out there's a workaround to this, where you wrap the entire function in a promise if you have any async calls, like so:
> <img alt="screen shot 2018-07-17 at 4 25 02 pm" width="442" src="https://user-images.githubusercontent.com/21372311/42846434-90976890-89de-11e8-982e-c41f3e99d276.png">
> 
> I believe the initial issue still stands, as the function shouldn't yield. But for other developers looking to just have a working solution now, do something like the above

Huge props to @kylebegovich for this solution - we've been using promises elsewhere, but wrapping the function fed to the agent in a promise works well, even if you have to use a throwaway `resolve()` function at the end.

I really think Dialogflow need to address this issue. For example:

```

**Comment by sarahdwyer** [comment]
As mentioned previously, returning a promise for any async operations is the intended design.

**Comment by AntonBogdan** [comment]
what about here ? agent . add is not working
function fallback(agent) {
return translate.translate(userMessage, options)
.then(results => {
const translation = results[0];
return run1(translation, userMessage, agent);
})
.catch(error => {
console.error(error);
agent.add("Sorry, I couldn't translate that!");
agent.add("Could you try again?");
return resolve();
});
}

async function run1(agent) {
// A unique identifier for the given sessionromanianText
return new Promise((resolve, reject) => {

  // bot call
  sessionClient.detectIntent(request).then(results => {
    const result = results[0].queryResult;
    console.log(`Detected intent ${JSON.stringify(result.intent.displayName)}`);

    if (result.intent.displayName !== "Default Fallback Intent") {
      agent.add(result.fulfillmentText);
      return resolve();
    } else {
      return run2(agent);
    }
  })
    .catch(error => {
      console.error(error);
      agent.add("Sorry, I couldn't translate that!");
      agent.add("Could you try again?");
      return resolve();
    });
});
}
async function run2(agent) {
return new Promise((resolve, reject) => {
sessionClient.detectIntent(request).then(results => {
const result = results[0].queryResult;
agent.add(result.fulfillmentText);
return resolve();
}).catch(error => {
console.error(error);
agent.add("")
return resolve();
});
});
}
