### ISSUE TITLE
no input - Reprompt

### ISSUE THREAD

**Issue by KoffeeToKode** [dialogflow/dialogflow-fulfillment-nodejs#99]
Hello,
If I add 2 reponses to my agent
```
agent.add('Response X.');
agent.add('Question X?');
```

and the user doesn't provide any input, the built-in reprompt will say something like :

> I didn't get that.
> Response X.

Instead of :
> I didn't get that.
> Response X.
> Question X ?

As soon as I create an intent with the **actions_intent_NO_INPUT** event in Dialogflow for a **specific** input context, I will have the following response for all of my intents no matter the input context :
> I didn't get that.

Any ideas on how I could have this when the user doesn't provide any input :
> I didn't get that.
> Question X ?

or this : 
> I didn't get that.
> Response X.
> Question X ?

**Comment by matthewayne** [comment]
Did you enabled fulfillment for your intent that has the `actions_intent_NO_INPUT` event?

**Comment by kofeetokode** [comment]
Yes. If I do that, I can save the response message in my webhook and use it to repeat the question to my user if the actions_intent_NO_INPUT event is triggered. 

However, for all of the intents that doesn't call my webhook, I could not save the intent response, so I could not repeat what have been said to the user.

So if I enable actions_intent_NO_INPUT event, for all the intent that didn't call my webhook, I can only have this :
> I didn't get that. 

And for all the intents that call my webhook, I can have something like this :

> I didn't get that.
> Response X.
> Question X ?

**Comment by matthewayne** [comment]
It seems you're using the Actions on Google integration.  Actions on Google [limits the number of simple responses to 2](https://developers.google.com/actions/assistant/responses) and seems to be ignoring your 3rd message.
